#!/bin/bash
# Purpose: grep for patterns (using cg) and then prompted for match to edit. Currently hardcoded to be gvim editor.
# Usage: cge [grep options] <pattern>
#
toolsDir=`which $0`
toolsDir=${toolsDir%/*}

$toolsDir/cg "$*" | awk '{print NR, " : ", $0}'
echo -n 'Select a line number to edit (blank to skip): '
read recordNumber
if [[ -n $recordNumber ]]; then
  vimArgs=`$toolsDir/cg "$*" | awk -v nr=$recordNumber 'BEGIN{FS=":"}{if (NR==nr) printf("%s +%d", $1,$2)}'`
  echo "vimArgs: $vimArgs"
  if [[ -n "$vimArgs" ]]; then
    gvim $vimArgs 2>&1 /dev/null
  fi
fi
