#!/bin/bash
#Usage: xdd <dir0> <dir1> [--maxdepth <maxdepth>] [--quiet|-q] <diff flags>

dir0="${1}"
shift
dir1="${1}"
shift
diffArgs=""
maxdepth=1
let quiet=0
while [[ $# > 0 ]]; do
  if [[ "--maxdepth" == "${1}" ]]; then
    shift
    maxdepth=${1}
  elif [[ "--quiet" == "${1}" || "-q" == "${1}" ]]; then
    let quiet=1
  else
    diffArgs+="${1}"
  fi
  shift
done

ff=` find ${dir0} -maxdepth ${maxdepth} -type f -printf '%P\n' `
ff+=` find ${dir1} -maxdepth ${maxdepth} -type f -printf '%P\n' `
#echo ${ff}

# Note: quotes are needed around stat, otherwise ? gets intepreted weirdly.
for f in ${ff}; do
  if [[ -f "${dir0}/${f}" ]]; then
    if [[ -f "${dir1}/${f}" ]]; then
      # We only care if there are differences, so always pass the -q flag
      diff -q ${diffArgs} "${dir0}/${f}" "${dir1}/${f}" >& /dev/null
      diffStat=${?}
      if [[ ${diffStat} == 0 ]]; then
          if (( ! ${quiet} )); then
              echo "IDENTICAL: ${dir0}/${f} and ${dir1}/${f} are the same"
          fi
      elif (( ${diffStat} == 1 )); then
        echo "DIFFER: ${dir0}/${f} and ${dir1}/${f} are different"
        #gvim --nofork -d "${dir0}/${f}" "${dir1}/${f}" >& /dev/null
        vim -d "${dir0}/${f}" "${dir1}/${f}"
      else
        echo "PROBLEM: couldn't compare ${dir0}/${f} and ${dir1}/${f}"
      fi
    else
      echo "MISSING: ${dir1}/${f} does not exist"
    fi
  else
    echo "MISSING: ${dir0}/${f} does not exist"
  fi
done
